-- MySQL Script generated by MySQL Workbench
-- Sat Jun 28 15:16:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema auraedition
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auraedition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auraedition` DEFAULT CHARACTER SET utf8mb3 ;
USE `auraedition` ;

-- -----------------------------------------------------
-- Table `auraedition`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `lname` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `hashed_password` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `role` ENUM('user', 'admin') CHARACTER SET 'utf8mb3' NOT NULL DEFAULT 'user',
  `registerd_date` DATETIME NULL DEFAULT NULL,
  `password_reset_token` VARCHAR(255) NULL DEFAULT NULL,
  `password_reset_expires` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`carts` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `cart_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `auraedition`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`makes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`makes` (
  `make_id` INT NOT NULL AUTO_INCREMENT,
  `make_name` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `make_image` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT '/Projects/AuraEdition/products/img/makes1.jpg',
  PRIMARY KEY (`make_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`model` (
  `model_id` INT NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `model_make_id` INT NOT NULL,
  PRIMARY KEY (`model_id`),
  INDEX `model_make_id_idx` (`model_make_id` ASC) VISIBLE,
  CONSTRAINT `model_make_id`
    FOREIGN KEY (`model_make_id`)
    REFERENCES `auraedition`.`makes` (`make_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `make_id` INT NOT NULL,
  `model_id` INT NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb3' NOT NULL,
  `stock` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_featured` TINYINT NULL DEFAULT '0',
  `is_popular` TINYINT NULL DEFAULT '0',
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY USING BTREE (`id`),
  INDEX `make_id` (`make_id` ASC) VISIBLE,
  INDEX `model_id` (`model_id` ASC) VISIBLE,
  CONSTRAINT `make_id`
    FOREIGN KEY (`make_id`)
    REFERENCES `auraedition`.`makes` (`make_id`),
  CONSTRAINT `model_id`
    FOREIGN KEY (`model_id`)
    REFERENCES `auraedition`.`model` (`model_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`cart_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`cart_items` (
  `cart_item_id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`cart_item_id`),
  INDEX `vehicle_idx` (`vehicle_id` ASC) VISIBLE,
  INDEX `cart_id_idx` (`cart_id` ASC) VISIBLE,
  CONSTRAINT `cart_id`
    FOREIGN KEY (`cart_id`)
    REFERENCES `auraedition`.`carts` (`cart_id`),
  CONSTRAINT `cart_item_vehicle`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `auraedition`.`vehicles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('pending', 'shipped', 'delivered') CHARACTER SET 'utf8mb3' NULL DEFAULT 'pending',
  `orderd_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `auraedition`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vehicle_id_idx` (`vehicle_id` ASC) VISIBLE,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `auraedition`.`orders` (`order_id`),
  CONSTRAINT `vehicle_id`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `auraedition`.`vehicles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`user_addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`user_addresses` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address_user_id` INT NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `address_user_id` (`address_user_id` ASC) VISIBLE,
  CONSTRAINT `address_user_id`
    FOREIGN KEY (`address_user_id`)
    REFERENCES `auraedition`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`vehicle_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`vehicle_images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_vehicle_id` INT NOT NULL,
  `image_path` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `is_primary` TINYINT NULL DEFAULT '0',
  `uploaded_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `image_vehicle_id` (`image_vehicle_id` ASC) VISIBLE,
  CONSTRAINT `image_vehicle_id`
    FOREIGN KEY (`image_vehicle_id`)
    REFERENCES `auraedition`.`vehicles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auraedition`.`wishlist_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auraedition`.`wishlist_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `wishlist_user_id` (`user_id` ASC) VISIBLE,
  INDEX `wishlist_vehicle_id` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `wishlist_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `auraedition`.`users` (`id`),
  CONSTRAINT `wishlist_vehicle_id`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `auraedition`.`vehicles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
